#pragma once

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MOVEMENTSPEED 250
#define GRAVITYSTRENGTH 300

#define JUMP_FORCE_DECREMENT 400
#define INITIAL_JUMP_FORCE 600

#define MAP_HEIGHT 13
#define MAP_WIDTH 32
#define LEVEL_WIDTH 1024
#define LEVEL_HEIGHT 416
#define SHAKE_DURATION 0.25

#define INJURED_TIME 2.5
#define KOOPA_SPEED 96
#define ANIMATION_DELAY 0.1

